default_stages: [pre-commit, pre-push]
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        types: [rust]
        language: system
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        entry: cargo check
        types: [rust]
        language: system
        pass_filenames: false

      - id: clippy
        name: clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        types: [rust]
        language: system
        pass_filenames: false
